### ISSUE TITLE
confusion in iou calculation

### ISSUE THREAD

**Issue by srihari-humbarwadi** [lars76/object-localization#10]
```
def iou(y_true, y_pred):
    xA = K.maximum(y_true[...,0], y_pred[...,0])
    yA = K.maximum(y_true[...,1], y_pred[...,1])
    xB = K.minimum(y_true[...,2], y_pred[...,2])
    yB = K.minimum(y_true[...,3], y_pred[...,3])

    interArea = (xB - xA) * (yB - yA)

    boxAArea = (y_true[...,2] - y_true[...,0]) * (y_true[...,3] - y_true[...,1])
    boxBArea = (y_pred[...,2] - y_pred[...,0]) * (y_pred[...,3] - y_pred[...,1])
    return K.clip(interArea / (boxAArea + boxBArea - interArea + K.epsilon()), 0, 1)
```
in the above function, y_true and y_pred are directly coming from the train data and the model respectively - which are scaled coordinates. Shouldn't the iou function convert them back to xmin, ymin, xmax,ymax and then calculate the iou?

**Comment by lars76** [comment]
Hi, minimum and maximum are homogeneous functions. This means min(k * x, k *y) = k * min(x,y) and we can pull out the coefficient k in the denominator and numerator which results in k/k * iou() = 1 * iou(). So scaling is no issue.

However, there were two other problems with the function:
- IOU shouldn't be calculated batch-wise (see https://github.com/keras-team/keras/issues/5794)
- the metric is not translation invariant and I confused x1 with width and y1 with height

The commit I just pushed should fix this.

**Comment by srihari-humbarwadi** [comment]
Yea right, i mis phrased my question. I intended to say that this iou doesn't account for the conversion from (x1,y1) (x2,y2) to (x,y)(w,h)
