### ISSUE TITLE
Error message from evaluate_performance.py

### ISSUE THREAD

**Issue by HuinaXu** [lars76/object-localization#4]
runfile('/Users/huinaxu/Desktop/object-localization-master/evaluate_performance.py', wdir='/Users/huinaxu/Desktop/object-localization-master')
Reloaded modules: generate_dataset, train_model
IoU on training data
2949/29499497/294911/294916/294920/294925/294930/294934/294939/294944/294949/294954/294958/294963/294968/294971/294976/294981/294986/294991/294996/2949101/2949106/2949110/2949114/2949120/2949123/2949126/2949132/2949135/2949138/2949143/2949146/2949149/2949153/2949158/2949163/2949168/2949171/2949174/2949177/2949180/2949183/2949186/2949189/2949193/2949198/2949203/2949208/2949213/2949217/2949222/2949227/2949230/2949233/2949236/2949239/2949242/2949247/2949252/2949257/2949262/2949266/2949271/2949276/2949281/2949284/2949287/2949290/2949293/2949296/2949299/2949302/2949306/2949311/2949315/2949319/2949323/2949328/2949333/2949338/2949343/2949346/2949349/2949354/2949358/2949362/2949366/2949370/2949373/2949376/2949380/2949383/2949386/2949390/2949395/2949400/2949404/2949410/2949415/2949419/2949424/2949427/2949431/2949435/2949439/2949443/2949447/2949451/2949456/2949461/2949466/2949471/2949476/2949481/2949486/2949491/2949495/2949499/2949504/2949509/2949513/2949517/2949521/2949524/2949527/2949530/2949534/2949539/2949543/2949547/2949553/2949558/2949563/2949568/2949572/2949577/2949582/2949587/2949592/2949596/2949601/2949608/2949612/2949617/2949622/2949627/2949632/2949637/2949642/2949646/2949649/2949653/2949659/2949664/2949669/2949674/2949679/2949682/2949685/2949688/2949691/2949695/2949699/2949703/2949708/2949712/2949715/2949719/2949723/2949727/2949732/2949737/2949741/2949745/2949749/2949753/2949758/2949763/2949767/2949771/2949775/2949778/2949782/2949785/2949788/2949791/2949796/2949801/2949806/2949810/2949814/2949818/2949822/2949827/2949832/2949837/2949841/2949847/2949851/2949855/2949860/2949864/2949868/2949873/2949878/2949882/2949886/2949890/2949894/2949900/2949904/2949908/2949912/2949915/2949920/2949924/2949928/2949932/2949937/2949942/2949947/2949951/2949955/2949959/2949963/2949967/2949970/2949972/2949976/2949980/2949984/2949988/2949992/2949996/29491000/29491004/29491008/29491013/29491017/29491021/29491025/29491029/29491033/29491037/29491041/29491046/29491050/29491054/29491058/29491062/29491066/29491070/29491073/29491076/29491079/29491084/29491088/29491091/29491095/29491099/29491102/29491106/29491110/29491114/29491118/29491122/29491126/29491130/29491134/29491138/29491142/29491146/29491150/29491154/29491158/29491162/29491166/29491170/29491174/29491178/29491182/29491186/29491190/29491194/29491198/29491202/29491205/29491210/29491214/29491219/29491223/29491227/29491231/29491235/29491240/29491244/29491248/29491252/29491256/29491260/29491264/29491268/29491272/29491276/29491280/29491284/29491294/29491311/29491336/29491367/29491411/29491478/29491582/29491739/29491996/29492402/2949
Avg IoU: 0.5732865147951192
Highest IoU: 0.9722222222222222
Lowest IoU: 0.0

IoU on validation data
737/737103/737
Avg IoU: 0.5246796910795323
Highest IoU: 0.9227614490772386
Lowest IoU: 0.0

Trying out unscaled image
images/Egyptian_Mau_167.jpg
Traceback (most recent call last):

  File "<ipython-input-12-9ebf5f0d4850>", line 1, in <module>
    runfile('/Users/---/Desktop/object-localization-master/evaluate_performance.py', wdir='/Users/---/Desktop/object-localization-master')

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/---/Desktop/object-localization-master/evaluate_performance.py", line 119, in <module>
    main()

  File "/Users/h---/Desktop/object-localization-master/evaluate_performance.py", line 108, in main
    pred = predict_image(path, model)

  File "/Users/---/Desktop/object-localization-master/evaluate_performance.py", line 42, in predict_image
    if im.shape[0] != IMAGE_SIZE:

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by lars76** [comment]
Seems like the file "images/Egyptian_Mau_167.jpg" isn't found. Maybe try using instead an absolute path (full path) in the csv files. It's an OS related error.

**Comment by HuinaXu** [comment]
Hi @lars76 ,
The file "images/Egyptian_Mau_167.jpg" was with some issue (not sure why this happened), hence it was recognized as "NoneType". After deleting this file from the folder, I was able to run through.
