### ISSUE TITLE
Issue found from all the commits. Might be my tensorflow version issue?

### ISSUE THREAD

**Issue by HuinaXu** [lars76/object-localization#5]
HHH-MBP:object-localization-master1 huinaxu$ python3 example_1/train_model.py
/Users/hhh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "example_1/train_model.py", line 130, in <module>
    main()
  File "example_1/train_model.py", line 125, in main
    model = create_model(IMAGE_SIZE, ALPHA)
  File "example_1/train_model.py", line 75, in create_model
    model = MobileNetV2(input_shape=(size, size, 3), include_top=False, alpha=alpha)
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/keras_applications/mobilenet_v2.py", line 355, in MobileNetV2
    expansion=1, block_id=0)
  File "/Users/hhh/anaconda3/lib/python3.6/site-packages/keras_applications/mobilenet_v2.py", line 461, in _inverted_res_block
    in_channels = inputs._keras_shape[-1]
AttributeError: 'Tensor' object has no attribute '_keras_shape'

**Comment by HuinaXu** [comment]
I am using Anaconda Python3.6. 
HuHH-MBP:object-localization-master1 hhh$ pip list
Package                            Version  
---------------------------------- ---------
imgaug                             0.2.6    
Keras                              2.2.2    
Keras-Applications                 1.0.4    
Keras-Preprocessing                1.0.2    
tensorflow                         1.11.0

**Comment by lars76** [comment]
Since you already have tensorflow 1.11, you can use the import "from tensorflow.keras.*" and keras is not needed anymore. Alternatively downgrade tensorflow to version 1.10 or try updating keras-applications/keras-preprocessing.

local/python-keras 2.2.2-5 [installed]
    Deep Learning library (convnets, recurrent neural networks, and more)
local/python-keras-applications 1.0.5-1 [installed]
    Applications module of the Keras deep learning library
local/python-keras-preprocessing 1.0.3-1 [installed]
    Preprocessing module of the Keras deep learning library
community/tensorflow 1.10.1-1 [installed]
    Library for computation using data flow graphs for scalable machine learning

**Comment by HuinaXu** [comment]
Issue solved with the correct package versions. thanks.
