### ISSUE TITLE
Modifying the model for multi object localization in an image

### ISSUE THREAD

**Issue by farshadopencv** [lars76/object-localization#9]
Hi. thanks for your amazing work. this model works very nice. But i have a question. when i feed  the model with an image with two or three cats, I have only one box and its accuracy is very low. How can I modify the   model for multi detection? what parts of the `train_model.py` or `evaluate_performance.py` should be changed for that? Your response will be highly appreciated.

**Comment by lars76** [comment]
Hi, example_1 and example_2 only support single-object detection. If you want to modify these two examples, you need to look at papers like YOLO, SSD etc.

Alternatively, use example_3 it supports multiple objects. You only have to modify the grouping function in test.py. YOLO is basically like example_3, except that it uses regression and some other fancy stuff (stronger architecture, anchor boxes etc.).
